### ISSUE TITLE
CU1 Ver lista de descubrimientos:

### ISSUE THREAD

**Issue by RodrigoJacznik** [frlp-utn-ingsoft/bookli#5]
**Descripción**: Permite listar los libros disponibles en la biblioteca.

**Actores**:
    Usuario

**Flujo normal:**
1. El usuario ingresa al sistema.
1. El sistema muestra una el listado de libros disponibles para leer.

**Flujo alternativo:**
1a. No existen libros en la lista
   1. El sistema muestra un mensaje indicando que no hay libros en la lista de descubrimientos.

**Puntos de extensión:**
1. Seleccionar un libro
   1. El usuario selecciona la opción para ver libro.
   1. <extend> CU 5

**Tareas**

- [x] Crear modelo del libro #15 
- [x] Crear API para listar libros descubrimiento #16
- [x] Crear UI lista de descubrimiento #17
